[package]
name = "noted2xero_web"
version = "0.1.0"
authors = ["Philip Rodrigues <phiroict@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
noted2xero_core = {path = "../noted2xero_core"}