[package]
name = "noted2xero_web"
version = "0.3.2"
authors = ["Philip Rodrigues <phiroict@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
noted2xero_core = {path = "../noted2xero_core"}
log = "0.4.14"
env_logger = "0.8.3"
uuid =  { version = "0.8.2", features = ["serde", "v4"] }
chrono = "0.4.19"
rocket = "0.4.7"
rocket-multipart-form-data = "0.9.6"
csv = "1.1.6"
serde = "1.0.125"
